import React, { useState, useEffect, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { listAdminCertificates, approveCertificate, rejectCertificate, revokeCertificate } from '../../services/adminService.js';
import { auth } from '../../services/api.js';

const STATUS_COLORS = {
  REQUESTED:    'bg-yellow-100 text-yellow-800',
  UNDER_REVIEW: 'bg-blue-100 text-blue-700',
  APPROVED:     'bg-green-100 text-green-700',
  ISSUED:       'bg-emerald-100 text-emerald-800',
  REJECTED:     'bg-red-100 text-red-700',
  REVOKED:      'bg-gray-200 text-gray-600',
};

// Generic confirm modal (reject / revoke — needs a reason field)
function ConfirmModal({ title, message, onConfirm, onCancel, confirmLabel, danger }) {
  const [reason, setReason] = useState('');
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4">
      <div className="bg-white rounded-2xl shadow-2xl max-w-md w-full p-6">
        <h3 className="text-lg font-heading font-bold text-gray-900 mb-2">{title}</h3>
        <p className="text-sm text-gray-600 mb-4">{message}</p>
        <textarea rows={3} placeholder="Reason (optional)" value={reason}
          onChange={e => setReason(e.target.value)}
          className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg mb-4 resize-none
                     focus:outline-none focus:ring-2 focus:ring-primary-500" />
        <div className="flex gap-3 justify-end">
          <button onClick={onCancel}
            className="px-4 py-2 text-sm font-medium text-gray-700 border border-gray-300 rounded-lg hover:bg-gray-50">
            Cancel
          </button>
          <button onClick={() => onConfirm(reason)}
            className={`px-4 py-2 text-sm font-semibold text-white rounded-lg
              ${danger ? 'bg-red-600 hover:bg-red-700' : 'bg-primary-800 hover:bg-primary-700'}`}>
            {confirmLabel}
          </button>
        </div>
      </div>
    </div>
  );
}

// Approve modal — cert number is auto-generated by backend; admin can optionally override it
function ApproveModal({ studentName, initialMarks, initialGrade, onConfirm, onCancel }) {
  const [marks,      setMarks]      = useState(initialMarks || '');
  const [grade,      setGrade]      = useState(initialGrade || '');
  const [certNumber, setCertNumber] = useState('');
  const [certError,  setCertError]  = useState('');

  const CERT_FORMAT = /^AICIT-\d{4}-\d{6}$/;

  const handleConfirm = () => {
    const trimmed = certNumber.trim().toUpperCase();
    if (trimmed && !CERT_FORMAT.test(trimmed)) {
      setCertError('Format must be AICIT-YYYY-XXXXXX  (e.g. AICIT-2026-000042)');
      return;
    }
    setCertError('');
    onConfirm({ marks: marks || null, grade: grade || null, customCertNumber: trimmed || null });
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4">
      <div className="bg-white rounded-2xl shadow-2xl max-w-md w-full p-6 space-y-4">
        <h3 className="text-lg font-heading font-bold text-gray-900">Approve Certificate</h3>
        <p className="text-sm text-gray-600">
          Approve and issue certificate for <span className="font-semibold">{studentName}</span>?
        </p>

        {/* Certificate Number */}
        <div>
          <label className="block text-xs font-semibold text-gray-500 uppercase mb-1">
            Certificate Number
            <span className="ml-1 text-gray-400 normal-case font-normal">(leave blank to auto-generate)</span>
          </label>
          <input
            type="text"
            value={certNumber}
            onChange={e => { setCertNumber(e.target.value); setCertError(''); }}
            placeholder="e.g. AICIT-2026-000042  or leave blank"
            className={`w-full px-3 py-2 text-sm border rounded-lg focus:outline-none focus:ring-2
              focus:ring-primary-500 font-mono tracking-wide
              ${certError ? 'border-red-400 bg-red-50' : 'border-gray-300'}`}
          />
          {certError && <p className="mt-1 text-xs text-red-600">{certError}</p>}
          {!certError && (
            <p className="mt-1 text-xs text-gray-400">Format: AICIT-YYYY-XXXXXX</p>
          )}
        </div>

        {/* Marks & Grade */}
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-xs font-semibold text-gray-500 uppercase mb-1">
              Marks <span className="text-gray-400 normal-case font-normal">(optional)</span>
            </label>
            <input type="text" value={marks} onChange={e => setMarks(e.target.value)}
              placeholder="e.g. 450/500"
              className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg
                         focus:outline-none focus:ring-2 focus:ring-primary-500" />
          </div>
          <div>
            <label className="block text-xs font-semibold text-gray-500 uppercase mb-1">
              Grade <span className="text-gray-400 normal-case font-normal">(optional)</span>
            </label>
            <input type="text" value={grade} onChange={e => setGrade(e.target.value)}
              placeholder="e.g. A+"
              className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg
                         focus:outline-none focus:ring-2 focus:ring-primary-500" />
          </div>
        </div>

        <p className="text-xs text-gray-400">
          A PDF certificate will be generated automatically upon approval.
        </p>
        <div className="flex gap-3 justify-end pt-1">
          <button onClick={onCancel}
            className="px-4 py-2 text-sm font-medium text-gray-700 border border-gray-300 rounded-lg hover:bg-gray-50">
            Cancel
          </button>
          <button onClick={handleConfirm}
            className="px-4 py-2 text-sm font-semibold text-white bg-green-600 hover:bg-green-700 rounded-lg transition-colors">
            ✅ Approve & Issue
          </button>
        </div>
      </div>
    </div>
  );
}

export default function AdminCertificatesPage() {
  const [certs,      setCerts]      = useState([]);
  const [pagination, setPagination] = useState({ totalElements: 0, totalPages: 0 });
  const [status,     setStatus]     = useState('REQUESTED');
  const [search,     setSearch]     = useState('');
  const [page,       setPage]       = useState(0);
  const [loading,    setLoading]    = useState(false);
  const [error,      setError]      = useState(null);
  const [modal,      setModal]      = useState(null); // { type: 'approve'|'reject'|'revoke', cert }

  const load = useCallback(async () => {
    setLoading(true); setError(null);
    try {
      const res = await listAdminCertificates({ page, size: 20, status, search });
      setCerts(res.data?.content ?? []);
      setPagination({ totalElements: res.data?.totalElements ?? 0, totalPages: res.data?.totalPages ?? 0 });
    } catch (err) { setError(err.message); }
    finally { setLoading(false); }
  }, [page, status, search]);

  useEffect(() => { load(); }, [load]);

  const doAction = async (action, id, payload = {}) => {
    try {
      if (action === 'approve') await approveCertificate(id, { marks: payload.marks || null, grade: payload.grade || null, customCertNumber: payload.customCertNumber || null });
      if (action === 'reject')  await rejectCertificate(id, payload.reason || '');
      if (action === 'revoke')  await revokeCertificate(id, payload.reason || '');
      setModal(null);
      load();
    } catch (err) { setError(err.message); setModal(null); }
  };

  const handleDownload = async (id, certNumber) => {
    const token = auth.getAdminToken();
    const res = await fetch(`/api/admin/certificates/${id}/download`, {
      headers: { Authorization: `Bearer ${token}` }
    });
    if (!res.ok) { alert('PDF not available.'); return; }
    const blob = await res.blob();
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href = url; a.download = `${certNumber}.pdf`; a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-5">
      {modal?.type === 'approve' && (
        <ApproveModal
          studentName={modal.cert.studentName}
          initialMarks={modal.cert.marks}
          initialGrade={modal.cert.grade}
          onCancel={() => setModal(null)}
          onConfirm={(payload) => doAction('approve', modal.cert.id, payload)}
        />
      )}
      {(modal?.type === 'reject' || modal?.type === 'revoke') && (
        <ConfirmModal
          title={modal.type === 'reject' ? 'Reject Certificate' : 'Revoke Certificate'}
          message={modal.type === 'reject'
            ? `Reject certificate request for ${modal.cert.studentName}?`
            : `Revoke certificate ${modal.cert.certificateNumber} for ${modal.cert.studentName}? It will show as REVOKED on public verification.`}
          onCancel={() => setModal(null)}
          onConfirm={(reason) => doAction(modal.type, modal.cert.id, { reason })}
          confirmLabel={modal.type === 'reject' ? 'Reject' : 'Revoke'}
          danger
        />
      )}

      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl font-heading font-bold text-primary-900">Certificates</h1>
          <p className="text-sm text-gray-500">{pagination.totalElements} total</p>
        </div>
      </div>

      {/* Filter tabs */}
      <div className="flex flex-wrap gap-2">
        {[['', 'All'], ['REQUESTED', 'Pending Review'], ['ISSUED', 'Issued'], ['REJECTED', 'Rejected'], ['REVOKED', 'Revoked']].map(([val, label]) => (
          <button key={val}
            onClick={() => { setStatus(val); setPage(0); }}
            className={`px-4 py-1.5 rounded-full text-sm font-semibold transition-colors
              ${status === val ? 'bg-primary-800 text-white' : 'bg-white text-gray-600 border border-gray-200 hover:border-primary-300'}`}>
            {label}
          </button>
        ))}
      </div>

      {/* Search */}
      <div className="relative max-w-sm">
        <svg className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z"/>
        </svg>
        <input type="search" placeholder="Search by cert number or student..."
          defaultValue={search}
          onKeyDown={e => { if (e.key==='Enter') { setSearch(e.target.value); setPage(0); }}}
          className="w-full pl-9 pr-4 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 bg-white"/>
      </div>

      {error && <div className="p-4 bg-red-50 border border-red-200 rounded-xl text-sm text-red-700">{error}</div>}

      <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
        {loading ? (
          <div className="flex items-center justify-center py-16 text-gray-400">
            <svg className="animate-spin w-6 h-6 mr-2" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
            </svg>Loading...
          </div>
        ) : certs.length === 0 ? (
          <div className="text-center py-16 text-gray-400">
            <div className="text-4xl mb-2">📜</div>
            <p>No certificates found</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-gray-50 border-b border-gray-100">
                  {['Cert Number','Student','Course','Institute','Status','Actions'].map(h => (
                    <th key={h} className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50">
                {certs.map(c => (
                  <tr key={c.id} className="hover:bg-gray-50">
                    <td className="px-4 py-3 font-mono text-xs">{c.certificateNumber || '—'}</td>
                    <td className="px-4 py-3 font-medium text-gray-900">{c.studentName}</td>
                    <td className="px-4 py-3 text-gray-600 max-w-[150px] truncate">{c.courseName}</td>
                    <td className="px-4 py-3 text-gray-600 max-w-[120px] truncate">{c.instituteName}</td>
                    <td className="px-4 py-3">
                      <span className={`px-2 py-0.5 rounded-full text-xs font-semibold ${STATUS_COLORS[c.status] || 'bg-gray-100 text-gray-600'}`}>
                        {c.status?.replace('_',' ')}
                      </span>
                    </td>
                    <td className="px-4 py-3">
                      <div className="flex gap-2 flex-wrap">
                        {(c.status === 'REQUESTED' || c.status === 'UNDER_REVIEW') && (
                          <>
                            <button onClick={() => setModal({ type: 'approve', cert: c })}
                              className="text-xs text-green-600 hover:underline font-semibold">Approve</button>                            <button onClick={() => setModal({ type: 'reject', cert: c })}
                              className="text-xs text-red-600 hover:underline font-semibold">Reject</button>
                          </>
                        )}
                        {c.status === 'ISSUED' && (
                          <>
                            <button onClick={() => handleDownload(c.id, c.certificateNumber)}
                              className="text-xs text-primary-600 hover:underline font-semibold">
                              {c.certificateType === 'TYPING'
                                ? '⬇ Typing Cert'
                                : '⬇ AICIT Cert'}
                            </button>
                            <button onClick={() => setModal({ type: 'revoke', cert: c })}
                              className="text-xs text-red-500 hover:underline font-semibold">Revoke</button>
                          </>
                        )}
                        <Link to={`/admin/certificates/${c.id}`}
                          className="text-xs text-gray-500 hover:underline font-medium">Detail</Link>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {pagination.totalPages > 1 && (
        <div className="flex items-center justify-between">
          <button disabled={page===0} onClick={() => setPage(p=>p-1)}
            className="px-4 py-2 text-sm font-medium text-gray-700 border border-gray-300 rounded-lg hover:bg-gray-50 disabled:opacity-40">← Previous</button>
          <span className="text-sm text-gray-500">Page {page+1} of {pagination.totalPages}</span>
          <button disabled={page>=pagination.totalPages-1} onClick={() => setPage(p=>p+1)}
            className="px-4 py-2 text-sm font-medium text-gray-700 border border-gray-300 rounded-lg hover:bg-gray-50 disabled:opacity-40">Next →</button>
        </div>
      )}
    </div>
  );
}
